import { EventData } from './EventsList';

// Shared Events Data - ใช้ร่วมกันทั้ง MobileEvents และ Campaign Overview
export const sharedEventsData: EventData[] = [
  {
    id: 1,
    name: 'Summer Shopping Festival',
    description: 'Shop and earn double points on all purchases during the summer sale',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600',
    startDate: '2025-06-01',
    endDate: '2025-08-31',
    participants: 1250,
    reward: '2x Points',
    category: 'Point Collection',
    isFavorite: false,
    terms: 'Valid for all product categories. Points will be credited within 24 hours.',
    status: 'Active',
    progress: 65,
  },
  {
    id: 2,
    name: 'Refer & Earn Program',
    description: 'Invite your friends and get rewarded for every successful referral',
    image: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=600',
    startDate: '2025-05-15',
    endDate: '2025-12-31',
    participants: 890,
    reward: '500 Points',
    category: 'Point Collection',
    isFavorite: true,
    terms: 'Referee must complete first purchase. Points awarded after 30 days.',
    status: 'Active',
    progress: 42,
  },
  {
    id: 3,
    name: 'Tech Gadget Bonanza',
    description: 'Exclusive deals on the latest smartphones, laptops, and smart home devices',
    image: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=600',
    startDate: '2025-06-10',
    endDate: '2025-07-10',
    participants: 2100,
    reward: 'Up to 40% Off',
    category: 'Electronics',
    isFavorite: false,
    terms: 'Limited stock available. First come, first served basis.',
    status: 'Active',
    progress: 78,
  },
  {
    id: 4,
    name: 'Fashion Week Special',
    description: 'Discover trending styles and get exclusive discounts on premium brands',
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea41f3cb?w=600',
    startDate: '2025-06-15',
    endDate: '2025-06-30',
    participants: 1680,
    reward: '30% Off + Free Shipping',
    category: 'Fashion & Accessories',
    isFavorite: true,
    terms: 'Valid on selected brands only. Cannot be combined with other offers.',
    status: 'Active',
    progress: 55,
  },
  {
    id: 5,
    name: 'Gourmet Food Festival',
    description: 'Taste premium cuisines from top restaurants with special member pricing',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600',
    startDate: '2025-07-01',
    endDate: '2025-07-15',
    participants: 950,
    reward: '25% Cashback',
    category: 'Food & Beverage',
    isFavorite: false,
    terms: 'Dine-in only. Reservation required 48 hours in advance.',
    status: 'Upcoming',
    progress: 0,
  },
  {
    id: 6,
    name: 'Wellness & Spa Retreat',
    description: 'Relax and rejuvenate with luxury spa packages at exclusive member rates',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600',
    startDate: '2025-07-05',
    endDate: '2025-07-20',
    participants: 780,
    reward: 'Free Upgrade',
    category: 'Health & Beauty',
    isFavorite: false,
    terms: 'Advance booking required. Subject to availability.',
    status: 'Upcoming',
    progress: 0,
  },
];

export const categories = [
  'All',
  'Point Collection',
  'Fashion & Accessories',
  'Electronics',
  'Food & Beverage',
  'Pets',
  'Health & Beauty',
  'Travel & Entertainment',
  'Others'
];
